version: '3.8'

services:
    server:
      build:
        context: ./server
        dockerfile: Dockerfile
      image: myapp-server
      #container_name: myapp-node-server
      command: npm start
      volumes:
        - ./server/:/server
      depends_on: 
        - redis
      links:
        - redis
      environment:
        - REDIS_URL=redis://cache
    lb: #Load Balancer
      image: dockercloud/haproxy
      links:
        - server
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 80:80
        - 81:1936
    client:
      build:
        context: ./client
        dockerfile: Dockerfile
      image: myapp-client
      stdin_open: true
      container_name: myapp-react-client
      command: npm start
      depends_on:
        - server
        - redis
      volumes:
        - ./client/src:/client/src
      links:
        - redis
      environment: 
        - CHOKIDAR_USEPOLLING=true
        - REDIS_URL=redis://cache
      ports:
        - "3000:3000"
    redis:
      image: "redis"
      ports: 
      - 6379:6379
      expose: 
        - 6379
      restart: 
        always
      container_name: cache
      

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
    